services:
  aistudio-websocket-app:
    image: aistudio-websocket
    build: .
    pull_policy: never
    container_name: aistudio-websocket-app
    environment:
      CAMOUFOX_INSTANCE_URL: ${CAMOUFOX_INSTANCE_URL:-}
      USER_COOKIE_1: ${USER_COOKIE_1:-}
      USER_COOKIE_2: ${USER_COOKIE_2:-}
      USER_COOKIE_3: ${USER_COOKIE_3:-}
      USER_COOKIE_4: ${USER_COOKIE_4:-}
    volumes:
      - ./cookies:/app/cookies:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
